# Generated by Django 4.0.6 on 2022-08-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('date_time', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('main', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=25, null=True)),
                ('icon', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'current_weather',
                'managed': False,
            },
        ),
    ]
